### PR TITLE
LPS-67147

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by briangreenwald** [comment]
Hey @hhuijser, was there a reason why this PR was sent over to me? Thanks!

**Comment by hhuijser** [comment]
Hey @briangreenwald 

I see you touched this file a number of times in the past couple of months, so I figured you probably know how this code is supposed to work and therefore I don't mind you having a look at it.
If you're okay with this, feel free to send to mhan for further review.

**Comment by briangreenwald** [comment]
@hhuijser 
Ah ok, that's what I had figured. Just wanted to make sure it wasn't a bug as a result of something I had previously changed. I'll be sure to push it over to Mike when I take a quick look. 

Thanks!

**Comment by briangreenwald** [comment]
mhan810/liferay-portal#1224

**Pull request closed without merging**
