### PR TITLE
[TECHNICAL-SUPPORT] LPS-62030 ldap.import.user.password.enabled=false is not working as expected

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-62030

Hi Brian,

MHan [asked](https://github.com/lipusz/liferay-portal/pull/105#issuecomment-174662183) me to forward this to you as you've been working on a related issue on https://issues.liferay.com/browse/LPS-44538.

Please take the further review of Norbi's changes and let he know if you have any concerns.

Here's Norbi's comment:

> In commit "LPS-62030 Apply new method" you might notice that whit this change, the scrennName based password will be determined after we check determine what the screenName should be. This is intentional, as it seemed to be another possible bug in case of auto-srceenname. However I didn't check that scenario.

Cheers,
Tibor

/cc @NorbertKocsis @mhan810

### CODE REVIEW

**Comment by lipusz** [comment]
Failure in SourceFormatterTest.testSourceFormatter

```
java.lang.Exception: plus: ../../../portal-impl/test/integration/com/liferay/portal/upgrade/v7_0_0/UpgradeKernelPackageTest.java 65
```

Not related.

**Comment by briangreenwald** [comment]
Scratch what I said above... Turns out I was reading something wrong so I'm digging a bit deeper.

Edit-
To clarify: The problem where the user's password will be regenerated at each login and overwrite an existing previously set local password is indeed still the problem. It's just the "fix" I mentioned isn't the solution.

**Comment by NorbertKocsis** [comment]
Hi Brian,

"Removing just the debug line but retaining the check for ldapUser.isAutoPassword() and the return if true would do the trick here."

Well I think it wouldn't. ldapUser.isAutoPassword() will return false only if the password is StringPool.BLANK. This is a problem as we never mention anywhere that you have to do anything about LDAP mappings to turn off password import and in fact we have a dedicated property for it. So it is very unlikely that ldapUser.isAutoPassword() will ever be true. Also in case of authentication that password will be what the user entered in the login form. For more information please refer to https://issues.liferay.com/browse/LPS-62172.

Also it is very unlikely that an admin would like their users to be able to have two valid passwords parallelly. If LDAP authentication is optional that means they have internal users in LDAP and they want those to authenticate against LDAP, and external users whom they don't want to export to LDAP and want them to authenticate against the portal. Those users won't be found in LDAP so this change won't affect them.

Also if password import is enabled then 'updateUserPassword' wont set it to an autogenerated password. If password import is disabled, and password should be autogenerated, then  overwrite the a locally set password (regardless how it happened) seem like a good choice.

And also if we keep this bailout, then we remove the possibility to switch between autogenerated and default passwords without requiring further maintenance actions from the admins. This also seems to be a problem because of lack of documentation.

Also update an autogenerated password to another one doesn't make much of a difference I think.

I hope this makes sense and please feel free to ask if something is not clear or I see something wrong here! :)

Br,
Norbert

**Comment by briangreenwald** [comment]
Hey Norbert,

You're right - it wouldn't do the trick (I replied shortly after my comment in the main thread noting that this was the case). What I had done when I thought things were "fixed" was place the return statement erroneously elsewhere and ended up seeing the functionality that I, personally, had expected. Whoops... Removing the debug line is perfectly valid!

Edit: After talking things through with Mike some more, it was decided that the autogen on each login should be fine. I didn't know that LR already prevents you from enabling export if autogen is on so there wouldn't be any sync problems that I was afraid of - sorry for any confusion!

We'll make sure the documentation is updated to reflect this functionality so that it's clearer to everyone going forward.

Thanks!
Brian
@mhan810

**Comment by lipusz** [comment]
Forwarded to https://github.com/mhan810/liferay-portal/pull/999

**Pull request closed without merging**
